### PR TITLE
Added model dir, Game.java file

### PR DESCRIPTION
**Pull request by IStallcup**
Added file for Game.java so we can get started eventually. No tests, design patterns etc., just getting us started.

### CODE REVIEW

**Comment by IStallcup** [comment]
Note - Travis fails as no Travis.yml file yet, but not a huge deal as Travis is not an integral part of beginning to code.

**Comment by athai** [comment]
Do you wanna add the travis.yml file into this PR?

**Comment by kannabanana** [comment]
After we add travis, we should do our uml, and paper prototypes

**Comment by IStallcup** [comment]
I think that if we merge it, the travis issue will be taken care of! :smile:

**Comment by athai** [comment]
Oh, nvm. You made this PR a week ago. How confusing.

**Pull request merged**
