### PR TITLE
Updates to html/css/js in view

### PR DESCRIPTION
**Pull request by leel8on**
Still some work to do, but this PR contains the large update to the view.

### CODE REVIEW

**Comment by leel8on** [comment]
Work towards #22

**Comment by athai** [comment]
It looks all right to me. I noticed that there isn't any logic that handles splitting and doubling down though?  Are you waiting on the back-end logic for that?

**Comment by leel8on** [comment]
Yep. Logic will come once I know what to call on the backend

**Comment by IStallcup** [comment]
Looks great so far! After work I'll try to add stringify stuff

**Comment by IStallcup** [comment]
Righto. I have deal up in a PR, though not implemented in the context of playing the game yet.

**Pull request merged**
